apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "scaphandre.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "scaphandre.name" . }}
  template:
    metadata:
      name: {{ template "scaphandre.name" . }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name:  {{ template "scaphandre.name" . }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
            {{- range $key, $value := .Values.scaphandre.args }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
            - {{ .Values.scaphandre.command }}
            {{- range $key, $value := .Values.scaphandre.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
        env:
        {{- if .Values.scaphandre.rustBacktrace }}
        - name: RUST_BACKTRACE
          value: '{{ .Values.scaphandre.rustBacktrace }}'
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.port }}
          hostPort: {{ .Values.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - mountPath: /proc
            name: proc
            readOnly: false
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      hostNetwork: true
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.userGroup }}
      serviceAccountName: {{ template "scaphandre.name" . }}
      volumes:
        - hostPath:
            path: /proc
            type: "Directory"
          name: proc
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
