{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "${VAR_WATT_PER_SECOND_TO_KWH}" }
  ]
 },
 "panels": [
  {
   "title": "Package Pod Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    }
   ]
  },
  {
   "title": "Node Package Power Consumption (W):",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(kepler_node_package_joules_total[1m])",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Summed Package Pod Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    }
   ]
  },
  {
   "title": "Node Package Power Consumption Sum (W):",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(kepler_node_package_joules_total[1m]))",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Pod Estimate Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    }
   ]
  },
  {
   "title": "Node Estimate Power Consumption (W):",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "irate(kepler_node_platform_joules_total[1m])",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  }
 ]
}