{
 "title": "Kubernetes power usage using Scaphandre",
 "description": "Show Kubernetes cluster power usage measured with Scaphandre.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "static_power_rapl", "query": "80" },
   { "name": "static_power_ipmi", "query": "250" }
  ]
 },
 "panels": [
  {
   "title": "IPMI Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scaph_ipmi_power_watts", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "RAPL Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Worker VM Attribution (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{cmdline=~\"^/usr/bin/kvm.*$\", cmdline=~\"^.*krth.*(-noise|-wrk).*$\"} / 1000000 > 0.1)",
     "legendFormat": "{{ cmdline }}"
    }
   ]
  },
  {
   "title": "Dynamic RAPL Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(scaph_host_power_microwatts / 1000000) - $static_power_rapl",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "VMs using > 0.1W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{cmdline=~\"^/usr/bin/kvm.*$\",cmdline=~\"^.*krth.*$\"} / 1000000 > 0.1",
     "legendFormat": "{{ cmdline }}"
    }
   ]
  },
  {
   "title": "Processes using > 0.1W",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{cmdline!~\"^/usr/bin/kvm.*$\"} / 1000000 > 1",
     "legendFormat": "{{ cmdline }}"
    }
   ]
  }
 ]
}